name: Linting and Testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
            
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
  
      - name: Install pnpm packages
        run: pnpm install
      
      - name: Run ESLint
        run: pnpm run lint

  building:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: Install pnpm packages
        run: pnpm install

      - name: Build Project
        run: pnpm run build
